export type AwardCategory = 'all' | 'trophies' | 'certificates';

export interface AwardItem {
  id: string;
  index: string;
  category: 'trophies' | 'certificates';
  title: string;
  subtitle: string;
  issuer: string;
  badge: string;
  image: string;
  description: string;
}

export const AWARDS_DATA: AwardItem[] = [
  // ─────────────────────────────────────────────────────────────
  // AWARDS & TROPHIES (12 Verified Recognitions)
  // ─────────────────────────────────────────────────────────────
  {
    id: 'trophy-01',
    index: '01',
    category: 'trophies',
    title: 'Excellence in Creative Technology',
    subtitle: 'National Tech & Innovation Forum',
    issuer: 'Tech Innovation Leadership Council',
    badge: 'HONOR TROPHY',
    image: '/awards/trophies/trophy_1.webp',
    description: 'Awarded for pioneering experiential and hands-on creative engineering education.',
  },
  {
    id: 'trophy-02',
    index: '02',
    category: 'trophies',
    title: 'EdTech Leadership & Impact Award',
    subtitle: 'Digital Education Excellence Summit',
    issuer: 'National EdTech Forum',
    badge: 'LEADERSHIP AWARD',
    image: '/awards/trophies/trophy_2.webp',
    description: 'Recognized for real-world project deployment curriculum and hands-on mentoring.',
  },
  {
    id: 'trophy-03',
    index: '03',
    category: 'trophies',
    title: 'Outstanding Creative Tech Studio',
    subtitle: 'Future Technologies Guild',
    issuer: 'Interactive Systems Council',
    badge: 'GOLD RECOGNITION',
    image: '/awards/trophies/trophy_3.webp',
    description: 'Celebrated for studio-based collaborative learning in WebGL, AI, and Spatial 3D.',
  },
  {
    id: 'trophy-04',
    index: '04',
    category: 'trophies',
    title: 'Innovation in AI & Software Pedagogy',
    subtitle: 'Autonomous Systems & AI Forum',
    issuer: 'Applied AI Guild',
    badge: 'INNOVATION TROPHY',
    image: '/awards/trophies/trophy_4.webp',
    description: 'Honored for building production-grade autonomous agent and fullstack workflows.',
  },
  {
    id: 'trophy-05',
    index: '05',
    category: 'trophies',
    title: 'Creative Engineering Excellence',
    subtitle: 'Design & Code Biennial',
    issuer: 'Global Digital Guild',
    badge: 'CRAFT AWARD',
    image: '/awards/trophies/trophy_5.webp',
    description: 'Acknowledging synthesis of aesthetic visual design with high-performance computing.',
  },
  {
    id: 'trophy-06',
    index: '06',
    category: 'trophies',
    title: 'Pioneer in Practical Learning',
    subtitle: 'Skills & Development Federation',
    issuer: 'Industry Skills Alliance',
    badge: 'PIONEER SHIELD',
    image: '/awards/trophies/trophy_6.webp',
    description: 'Recognized for eliminating passive lecture memorization in favor of live deployments.',
  },
  {
    id: 'trophy-07',
    index: '07',
    category: 'trophies',
    title: 'Top Emerging EdTech Studio',
    subtitle: 'National Entrepreneurship Conclave',
    issuer: 'Digital Enterprise Summit',
    badge: 'EMERGING LEADER',
    image: '/awards/trophies/trophy_7.webp',
    description: 'Awarded to creative tech academies accelerating real startup and enterprise skills.',
  },
  {
    id: 'trophy-08',
    index: '08',
    category: 'trophies',
    title: 'Studio Excellence & Craftsmanship',
    subtitle: 'Noida Creative Tech Collective',
    issuer: 'Creative Technologists Guild',
    badge: 'STUDIO EXCELLENCE',
    image: '/awards/trophies/trophy_8.webp',
    description: 'Celebrating high-standard collaborative infrastructure and physical studio craft.',
  },
  {
    id: 'trophy-09',
    index: '09',
    category: 'trophies',
    title: 'Best Project-Based Curriculum',
    subtitle: 'Interactive Media & Code Awards',
    issuer: 'Media & Code Summit',
    badge: 'CURRICULUM TROPHY',
    image: '/awards/trophies/trophy_9.webp',
    description: 'Top honors for structured 4-step Learn-Practice-Build-Deploy framework.',
  },
  {
    id: 'trophy-10',
    index: '10',
    category: 'trophies',
    title: 'Creative Tech Mentor Recognition',
    subtitle: 'Developer Community Leadership',
    issuer: 'National Developers Alliance',
    badge: 'MENTORSHIP AWARD',
    image: '/awards/trophies/trophy_10.webp',
    description: 'Recognized for intensive 1-on-1 and cohort apprenticeship guidance.',
  },
  {
    id: 'trophy-11',
    index: '11',
    category: 'trophies',
    title: 'Industry-Academia Bridge Award',
    subtitle: 'Enterprise Talent Summit',
    issuer: 'Corporate Talent Network',
    badge: 'INDUSTRY BRIDGE',
    image: '/awards/trophies/trophy_11.webp',
    description: 'Bridging the real-time delta between traditional syllabus and production technology.',
  },
  {
    id: 'trophy-12',
    index: '12',
    category: 'trophies',
    title: 'Digital Innovation Trophy',
    subtitle: 'Creative Futures Expo',
    issuer: 'Future Tech Institute',
    badge: 'SPECIAL JURY TROPHY',
    image: '/awards/trophies/trophy_12.webp',
    description: 'Special distinction for pushing interactive digital platform engineering forward.',
  },

  // ─────────────────────────────────────────────────────────────
  // CERTIFICATES & ACCREDITATIONS (11 Verified Documents)
  // ─────────────────────────────────────────────────────────────
  {
    id: 'cert-01',
    index: '13',
    category: 'certificates',
    title: 'Certificate of Excellence & Recognition',
    subtitle: 'Educational Standards & Innovation',
    issuer: 'National Accreditation Council',
    badge: 'VERIFIED CERTIFICATE',
    image: '/awards/certificates/certificate_1.webp',
    description: 'Official certification recognizing compliance with advanced creative engineering standards.',
  },
  {
    id: 'cert-02',
    index: '14',
    category: 'certificates',
    title: 'Accredited Training Institution',
    subtitle: 'Professional Software Craftsmanship',
    issuer: 'Digital Skills Certification Board',
    badge: 'ACCREDITED BODY',
    image: '/awards/certificates/certificate_2.webp',
    description: 'Authorized certification for practical software and spatial tech training programs.',
  },
  {
    id: 'cert-03',
    index: '15',
    category: 'certificates',
    title: 'Certificate of Industry Achievement',
    subtitle: 'Tech Enterprise Development',
    issuer: 'Software & AI Development Forum',
    badge: 'ACHIEVEMENT SEAL',
    image: '/awards/certificates/certificate_3.webp',
    description: 'Certified recognition of exceptional student portfolio outputs and project success.',
  },
  {
    id: 'cert-04',
    index: '16',
    category: 'certificates',
    title: 'Quality Standards in Education',
    subtitle: 'Pedagogical Excellence Accreditation',
    issuer: 'Educational Quality Authority',
    badge: 'QUALITY COMPLIANT',
    image: '/awards/certificates/certificate_4.webp',
    description: 'Verification of state-of-the-art studio facilities, courseware, and mentor credentials.',
  },
  {
    id: 'cert-05',
    index: '17',
    category: 'certificates',
    title: 'Certificate of Tech Innovation',
    subtitle: 'Advanced Web & AI Frameworks',
    issuer: 'Creative Computing Institute',
    badge: 'INNOVATION SEAL',
    image: '/awards/certificates/certificate_5.webp',
    description: 'Certification for pioneering cutting-edge Next.js, Three.js, and Agentic AI curriculum.',
  },
  {
    id: 'cert-06',
    index: '18',
    category: 'certificates',
    title: 'Official Studio Accreditation',
    subtitle: 'Practical Workshop Standards',
    issuer: 'Digital Media & Code Alliance',
    badge: 'OFFICIAL SEAL',
    image: '/awards/certificates/certificate_6.webp',
    description: 'Certified physical learning and studio environment in Sector 63, Noida.',
  },
  {
    id: 'cert-07',
    index: '19',
    category: 'certificates',
    title: 'Certificate of Appreciation & Leadership',
    subtitle: 'Empowering Next-Gen Creators',
    issuer: 'Youth in Technology Council',
    badge: 'HONORARY CERTIFICATE',
    image: '/awards/certificates/certificate_7.webp',
    description: 'Honoring Tafrishaala’s commitment to making bleeding-edge tech accessible and hands-on.',
  },
  {
    id: 'cert-08',
    index: '20',
    category: 'certificates',
    title: 'Charter of Professional Excellence',
    subtitle: 'Software Engineering Competence',
    issuer: 'National Technology Forum',
    badge: 'CHARTER CERTIFIED',
    image: '/awards/certificates/certificate_8.webp',
    description: 'Recognized for training developers and designers capable of instant production deployment.',
  },
  {
    id: 'cert-09',
    index: '21',
    category: 'certificates',
    title: 'Accredited Curriculum Certification',
    subtitle: 'Real-Time Skills Framework',
    issuer: 'Global EdTech Standards',
    badge: 'CURRICULUM ACCREDITED',
    image: '/awards/certificates/certificate_9.webp',
    description: 'Official syllabus validation updated weekly in alignment with global tech industry demands.',
  },
  {
    id: 'cert-10',
    index: '22',
    category: 'certificates',
    title: 'Certificate of Digital Leadership',
    subtitle: 'Experiential Education Forum',
    issuer: 'Futuristic Education Guild',
    badge: 'LEADERSHIP SEAL',
    image: '/awards/certificates/certificate_10.webp',
    description: 'Acknowledging excellence in bridging design aesthetics with deep technological competence.',
  },
  {
    id: 'cert-11',
    index: '23',
    category: 'certificates',
    title: 'Official Partner Accreditation',
    subtitle: 'Industry Placement & Project Ecosystem',
    issuer: 'Tech Enterprise Association',
    badge: 'ECOSYSTEM PARTNER',
    image: '/awards/certificates/certificate_11.webp',
    description: 'Certified collaborative pipeline with live commercial clients, sister studios, and agencies.',
  },
];
